### ISSUE TITLE
Which A/B Port

### ISSUE THREAD

**Issue by phoenix1589** [Frankkkkk/python-pylontech#28]
I'll preface this with I've not yet got these batteries, but I'm currently doing some research into them.

The battery looks to have a A/CAN and B/RS485 port. The pinout from the manual suggests both ports have CAN on pins 4/5 and RS485 on pins 7/8.

Do you know if I can use either port with this library? I think the inverter needs to use RS485 to the battery, which would use one of the ports.

**Comment by Frankkkkk** [comment]
Hi,
This library only supports the RS485 ports.
My guess is that the pinout is the same on both ports, but they are each wired to their own protocol respectively.
You could try to plug into the CAN port, but I don't guarantee anything :-)

Kind regards
